### PR TITLE
A series of small fixes and improvements

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
Besides a couple of fixes and the addition of some basic tests and CI, this adds a new `isGitTreeDirty` API.

### CODE REVIEW

**Comment by ypid** [comment]
LGTM. Thanks for the passing build :+1: I have not used Haxe for some time now. I will do a release later. I have no idea where haxe saved my haxelib password Oo. I will keep you updated but it can take a few weeks.

**Comment by jonasmalacofilho** [comment]
To reset the haxelib password you can contact Andy Li (source: [haxelib#415, comment](https://github.com/HaxeFoundation/haxelib/issues/415#issuecomment-376502746)).

If you need some help, I would be happy to maintain the library with you.  You can add me as a contributor to haxelib and/or this repository... my username is `jonasmalacofilho` on both.

**Comment by ypid** [comment]
Thanks! I will check it out. I have in mind that the password was saved in some file in my GNU/Linux home? Can you refresh my memory?

**Comment by jonasmalacofilho** [comment]
I don't see anything in the current haxelib code to suggest that, but I haven't check the history in much depth.

You could search for `~/.haxelib*` files or check what's inside the folder that `~/.haxelib` points to.

**Pull request merged**
